jobs:
  - template: /.ci/templates/job.yaml
    parameters:
      name: Test
      steps:
        - bash: |
            set -ex
            coverage run -a -m bgmi.main install
            bgmi -h
            coverage run -a -m pytest tests --cache-requests --junitxml tmp/junit/test_report.xml --reruns=3 --reruns-delay=0.1

          env:
            DEBUG: mikan-dump
            BGMI_PATH: $(Pipeline.Workspace)/.bgmi

        - task: PublishTestResults@2
          condition: succeededOrFailed()
          inputs:
            testResultsFiles: tmp/junit/test_*.xml
            testRunTitle: Publish test results for Python $(python_version)

        - task: PublishBuildArtifacts@1
          condition: always()
          inputs:
            pathToPublish: $(Pipeline.Workspace)/.bgmi/tmp
            artifactName: dump-$(platform)-$(python_version)

        - bash: |
            export BUILD_SOURCEBRANCHNAME=${BRANCH#"refs/heads/"} # fix azure branch source name
            bash <(curl -s https://codecov.io/bash) -Z -F "py${PYV/./}" -F "${PLATFORM}" -C $(Build.SourceVersion)
          name: Codecov
          env:
            PYV: $(python_version)
            BRANCH: $(Build.SourceBranch)
            PLATFORM: $(platform)
